server:
  host: 0.0.0.0
  port: 8000
  queue: rabbitmq://message_queue:5672/

client:
  host: 0.0.0.0
  port: 8000
  path: sample.mind.gz

saver:
  queue: rabbitmq://message_queue:5672/
  db: mongodb://db:27017/

api:
  db: mongodb://db:27017/
  host: 0.0.0.0
  port: 5000

parsers:
  queue: rabbitmq://message_queue:5672/

gui:
  host: 0.0.0.0
  port: 3000
  api_host: 0.0.0.0
  api_port: 5000
